### ISSUE TITLE
Ducking and pressing forward makes you Roll?

### ISSUE THREAD

**Issue by PixelPiledriver** [csclyde/Frauki#11]
It just seems really weird.
I do it when trying to go into a small hole.
but i end up rolling over the hole instead.

**Comment by csclyde** [comment]
it is intentional, but I will definitely reconsider. The idea was that you can crouch -> roll -> stabby in a fluid "hadouken" motion. I guess the expectation is that being crouched would make you move slower! I will put more thought into this.
