### ISSUE TITLE
Ruins music does not update when I change it! It still plays the old music for some reason. No sense is made.

### ISSUE THREAD

**Issue by munderwoods** [csclyde/Frauki#15]

**Comment by csclyde** [comment]
The old song is probably cached. Keep the javascript console open while you're working (ctrl+shift+j). Then, in the top right corner of the console is a little gear icon. Click that and then check "Disable Cache (While DevTools is Open)".

**Comment by csclyde** [comment]
If this fixed it, go ahead and close the issue
