### ISSUE TITLE
Can't cancel air hike animation to attack

### ISSUE THREAD

**Issue by munderwoods** [csclyde/Frauki#17]
This sucks

**Comment by csclyde** [comment]
Do you think if you attack while in an air hike, it should do the overhead attack? Or should it do the forward slash? Currently, if you hold up and attack while jumping, it does the overhead attack and gives you the same boost as a double jump. So this would be kind of an alternative way to do that, without modifying the functionality of the double jump.

**Comment by csclyde** [comment]
For now, it will only do the up attack if youre holding up. Either way it cancels the air hike animation
