### ISSUE TITLE
Moving Butt Stomp

### ISSUE THREAD

**Issue by PixelPiledriver** [csclyde/Frauki#7]
You can move left or right while the Butt Stomp is charging.
You can also move after colliding.
It might be cool to be able to control as you fall a little.
But right now it is just a constant speed no matter what phase of the animation you are in and it feels weird.

**Comment by csclyde** [comment]
They can no longer move while doing the attack. Feels much better. There is very slight movement during the fall art, might bum it up more and see how it feels.
